CREATE TABLE IF NOT EXISTS DIM_AGENCY
(
AGENCY_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
CUSTOMER_ID TEXT,
AGENCY_NAME TEXT
);

CREATE TABLE IF NOT EXISTS  DIM_LOCALITY
(
LOCALITY_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
LOCALITY_NAME TEXT,
DISTRICT_NAME TEXT,
CITY_ID INTEGER
);

CREATE TABLE IF NOT EXISTS  DIM_COUNTRY
(
COUNTRY_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
COUNTRY_NAME TEXT);

CREATE TABLE IF NOT EXISTS  DIM_CITY
(
CITY_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
CITY_NAME TEXT,
COUNTRY_ID INTEGER
);

CREATE TABLE IF NOT EXISTS  DIM_FLAT_FACILTIY
(
FLAT_FACILITY_ID INTEGER NOT NULL PRIMARY KEY,
HAS_BALCONY INTEGER,
HAS_BUILT_IN_KITCHEN INTEGER,
HAS_GARDEN INTEGER,
HAS_CELLAR INTEGER,
HAS_GUEST_TOILET INTEGER,
HAS_LIFT INTEGER
);

CREATE TABLE IF NOT EXISTS  DIM_FLAT_TYPE
(
FLAT_TYPE_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
FLAT_TYPE_NAME TEXT
);
