CREATE TABLE IF NOT EXISTS STAGE_CONTACT_DETAILS
(
RealEstate_ID,
CustomerID TEXT,
Firstname TEXT,
Lastname TEXT,
HouseNumber TEXT,
Street TEXT,
City TEXT,
Postcode INTEGER,
Company TEXT,
CountryCode TEXT,
Email TEXT,
HomepageUrl TEXT,
PortraitUrl TEXT,
RealtorLogo TEXT,
Salutation TEXT,
Title TEXT,
CellPhoneNumber TEXT,
CellPhoneNumberAreaCode TEXT,
CellPhoneNumberCountryCode TEXT,
CellPhoneNumberSubscriber TEXT,
FaxNumber TEXT,
FaxNumberAreaCode TEXT,
FaxNumberCountryCode TEXT,
FaxNumberSubscriber TEXT,
PhoneNumber TEXT,
PhoneNumberAreaCode TEXT,
PhoneNumberCountryCode TEXT,
PhoneNumberSubscriber TEXT
);

CREATE TABLE IF NOT EXISTS STAGE_FLAT_GEOHIERARCHY
(
RealEstate_ID INTEGER,
city_fullGeoCodeId INTEGER,
city_geoCodeId INTEGER,
city_name TEXT,
continent_fullGeoCodeId INTEGER,
continent_geoCodeId INTEGER,
country_fullGeoCodeId INTEGER,
country_geoCodeId INTEGER,
country_name TEXT,
neighbourhood_geoCodeId INTEGER,
quarter_fullGeoCodeId INTEGER,
quarter_geoCodeId INTEGER,
quarter_name TEXT,
region_fullGeoCodeId INTEGER,
region_geoCodeId INTEGER,
Region_name TEXT
);

CREATE TABLE IF NOT EXISTS STAGE_FLAT_ADDRESS_DETAILS
(
RealEstate_ID INTEGER,
HouseNumber TEXT,
Postcode TEXT,
Quarter TEXT,
Street TEXT,
Latitude TEXT,
Longitude TEXT
);

CREATE TABLE IF NOT EXISTS STAGE_FLAT_DETAILS
(
RealEstate_ID INTEGER PRIMARY KEY,
CustomerID INTEGER,
ApartmentType INTEGER,
AssistedLiving INTEGER,
Attachments TEXT,
Balcony INTEGER,
BaseRent REAL,
BuildingEnergyRatingType TEXT,
BuiltInKitchen INTEGER,
CalculatedTotalRent REAL,
CalculatedTotalRentScope TEXT,
Cellar TEXT,
CertificateOfEligibilityNeeded INTEGER,
Condition TEXT,
ConstructionYear INTEGER,
ConstructionYearUnknown INTEGER,
HasCourtage TEXT,
CreationDate TEXT,
Deposit TEXT,
DescriptionNote TEXT,
EnergyCertificateAvailability TEXT,
EnergyCertificateCreationDate TEXT,
EnergyCertificate_energyEfficiencyClass TEXT,
EnergyConsumptionContainsWarmWater TEXT,
EnergyPerformanceCertificate INTEGER,
EnergySourceEnev2014 TEXT,
ExternalId TEXT,
FiringTypes TEXT,
Floor INTEGER,
Floorplan INTEGER,
FreeFrom TEXT,
FurnishingNote TEXT,
Garden INTEGER,
GroupNumber INTEGER,
GuestToilet TEXT,
HandicappedAccessible TEXT,
HeatingCosts REAL,
HeatingCostsInServiceCharge TEXT,
HeatingType TEXT,
HeatingTypeEnev2014 TEXT,
InteriorQuality TEXT,
LastModificationDate TEXT,
LastRefurbishment TEXT,
Lift INTEGER,
LivingSpace REAL,
LocationNote TEXT,
NumberOfBathRooms INTEGER,
NumberOfBedRooms INTEGER,
NumberOfFloors INTEGER,
NumberOfParkingSpaces INTEGER,
NumberOfRooms INTEGER,
OtherNote TEXT,
ParkingSpacePrice REAL,
ParkingSpaceType TEXT,
PetsAllowed INTEGER,
ServiceCharge REAL,
State TEXT,
ThermalCharacteristic TEXT,
Title TEXT,
TotalRent REAL,
UsableFloorSpace REAL,
UseAsFlatshareRoom INTEGER
);

CREATE TABLE IF NOT EXISTS STAGE_ADVERTISEMENT_DETAILS
(
Realestate_id integer not null primary key,
IsActive INTEGER,
Creation_date TEXT,
Modified_date TEXT,
HasPictures INTEGER 
);